# Generated by Django 3.1.5 on 2021-02-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdbtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_dob',
            field=models.CharField(max_length=100),
        ),
    ]
