# Generated by Django 3.1.5 on 2021-03-06 12:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_created', models.DateTimeField(default=datetime.datetime(2021, 3, 6, 17, 39, 20, 933325))),
                ('totalamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=255)),
                ('phoneno1', models.CharField(max_length=10)),
                ('phoneno2', models.CharField(max_length=10)),
                ('expected_delivery', models.DateTimeField(default=datetime.datetime(2021, 3, 12, 17, 39, 20, 933825))),
                ('payment_type', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
    ]
