# Generated by Django 3.1.5 on 2021-03-26 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderhandling', '0002_auto_20210326_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 20, 2, 22, 457047)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 26, 20, 2, 22, 456047)),
        ),
    ]
